---

#############################
#############################
## JavaScript Linter rules ##
#############################
#############################

#########
# Rules #
#########
rules: {
  "semi": ["error", "always"]
}